version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: xfjerj
      POSTGRES_PASSWORD: 12341234
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  message-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=xfjerj
      - DB_PASSWORD=12341234
      - REDIS_URL=redis:6379

  realtime-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=xfjerj
      - DB_PASSWORD=12341234
      - REDIS_URL=redis:6379

  history-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=xfjerj
      - DB_PASSWORD=12341234

volumes:
  postgres_data:
